# Generated by Django 3.2.5 on 2022-02-26 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0002_register_table_dept'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register_table',
            name='dept',
        ),
    ]
